title: Before we started going to school (1983-1988)
sub_title: at St. Matthews
cover: TurboScan2-020.jpg
sections:
  - type: pictures-group
    images:
      - - TurboScan2-020.jpg
        - TurboScan2-021.jpg
        - TurboScan2-022.jpg
      - - TurboScan2-023.jpg
        - TurboScan2-024.jpg
        - TurboScan2-025.jpg
      - - TurboScan2-026.jpg
        - TurboScan2-027.jpg
        - TurboScan2-028.jpg
      - - TurboScan2-029.jpg
        - TurboScan2-030.jpg
        - TurboScan2-031.jpg
      - - TurboScan2-032.jpg
        - TurboScan2-033.jpg
        - TurboScan2-034.jpg
      - - TurboScan2-035.jpg
        - TurboScan2-036.jpg
        - TurboScan2-037.jpg
      - - TurboScan2-038.jpg
        - TurboScan2-039.jpg
        - TurboScan2-040.jpg
      - - TurboScan2-041.jpg
        - TurboScan2-042.jpg
        - TurboScan2-043.jpg
      - - TurboScan2-044.jpg
        - TurboScan2-045.jpg
        - TurboScan2-046.jpg
      - - TurboScan2-047.jpg
        - TurboScan2-048.jpg
        - TurboScan2-049.jpg
      - - TurboScan2-050.jpg
        - TurboScan3-000.jpg
        - TurboScan3-001.jpg
      - - TurboScan3-002.jpg
        - TurboScan3-003.jpg
        - TurboScan3-004.jpg
      - - TurboScan3-005.jpg
        - TurboScan3-006.jpg
        - TurboScan3-007.jpg
      - - TurboScan3-008.jpg
        - TurboScan3-009.jpg
        - TurboScan3-010.jpg
      - - TurboScan3-021.jpg
        - TurboScan3-022.jpg
        - TurboScan3-023.jpg
      - - TurboScan3-024.jpg
        - TurboScan3-097.jpg
        - TurboScan3-098.jpg
      - - TurboScan3-099.jpg
        - TurboScan3-100.jpg
        - TurboScan3-101.jpg
      - - TurboScan3-102.jpg
        - TurboScan3-103.jpg
        - TurboScan3-104.jpg
      - - TurboScan3-105.jpg
        - TurboScan3-106.jpg
        - TurboScan3-123.jpg
      - - TurboScan3-124.jpg
        - TurboScan3-125.jpg
        - TurboScan3-126.jpg
      - - TurboScan3-127.jpg
        - TurboScan3-128.jpg
        - TurboScan3-130.jpg
      - - TurboScan3-158.jpg
        - TurboScan3-160.jpg
        - TurboScan3-162.jpg
      - - TurboScan3-163.jpg
        - TurboScan3-164.jpg
        - TurboScan3-165.jpg
      - - TurboScan3-166.jpg
        - TurboScan3-169.jpg
        - TurboScan3-170.jpg
      - - TurboScan3-171.jpg
        - TurboScan3-172.jpg
        - TurboScan3-181.jpg
      - - TurboScan4-000.jpg
        - TurboScan4-001.jpg
        - TurboScan4-002.jpg
      - - TurboScan4-003.jpg
        - TurboScan4-004.jpg
        - TurboScan4-005.jpg
      - - TurboScan4-006.jpg
        - TurboScan4-007.jpg
        - TurboScan4-008.jpg
      - - TurboScan4-009.jpg
        - TurboScan4-010.jpg
        - TurboScan4-022.jpg
      - - TurboScan4-023.jpg
        - TurboScan4-024.jpg
        - TurboScan4-025.jpg
