title: Of Elementary School Age (1988-1999)
sub_title: at St. Matthews
date: 1988-09-01
cover: TurboScan3-011.jpg
sections:
  - type: pictures-group
    images:
      - - name: 'Photo Nov 22, 7 57 05 PM (2).jpg'
          text: ''
        - name: 'Photo Nov 22, 7 57 06 PM.jpg'
          text: ''
        - name: TurboScan3-011.jpg
          text: '2/24/1992 Kjell School Photo 1st Grade'
      - - name: TurboScan3-012.jpg
          text: '6/4/1992 Kjell and Isaac in 1st grade'
        - name: TurboScan3-013.jpg
          text: "2/2/1997 Emmett (age 13) at Alfys Pizza for Basketball Party"
        - name: TurboScan3-014.jpg
          text: '2/2/1997 Emmett (age 13) at Alfys Pizza for Basketball Party'
      - - name: TurboScan3-015.jpg
          text: ''
        - name: TurboScan3-016.jpg
          text: ''
        - name: TurboScan3-018.jpg
          text: ''
      - - name: TurboScan3-019.jpg
          text: ''
        - name: TurboScan3-020.jpg
          text: ''
        - name: TurboScan3-026.jpg
          text: 'September 1999 Kjell (age 14) at St. Matthews Church in 8th Grade'
      - - name: TurboScan3-027.jpg
          text: 'September 1999 Kjell (age 14) at St. Matthews Church in 8th Grade'
        - name: TurboScan3-028.jpg
          text: 'September 1999 Kjell (age 14) at St. Matthews Church in 8th Grade'
        - name: TurboScan3-029.jpg
          text: ''
      - - name: TurboScan3-030.jpg
          text: ''
        - name: TurboScan3-031.jpg
          text: ''
        - name: TurboScan3-032.jpg
          text: ''
      - - name: TurboScan3-033.jpg
          text: ''
        - name: TurboScan3-034.jpg
          text: ''
        - name: TurboScan3-035.jpg
          text: ''
      - - name: TurboScan3-036.jpg
          text: ''
        - name: TurboScan3-037.jpg
          text: ''
        - name: TurboScan3-038.jpg
          text: ''
      - - name: TurboScan3-116.jpg
          text: "June 5, 1998 Kjell's 13th Birthday Party with Justin G, Paul Suh, Patrick Walton"
        - name: TurboScan3-117.jpg
          text: "June 5, 1998 Kjell's 13th Birthday Party with Justin G, Paul Suh, Patrick Walton, Mike Olson"
        - name: TurboScan3-118.jpg
          text: "June 5, 1998 Kjell's 13th Birthday Party with Delicious Cake"
      - - name: TurboScan3-119.jpg
          text: 'Probably 1998'
        - name: TurboScan3-122.jpg
          text: '10/30/98 Kyle Wolf, Justin Lazaro, Chris Carroll, Kjell Connelly, Nik Blukis, Ian Wakefield, Geoff Gunderson, Brandon Howard, Mike Olson, Paul Suh'
        - name: TurboScan3-131.jpg
          text: '1997 Walter and Wi-Gung'
      - - name: TurboScan3-132.jpg
          text: 'Probably 1998'
        - name: TurboScan3-133.jpg
          text: 'Probably 1998'
        - name: TurboScan3-134.jpg
          text: 'Probably 1998'
      - - name: TurboScan3-135.jpg
          text: 'Probably 1998'
        - name: TurboScan3-136.jpg
          text: 'Probably 1998'
        - name: TurboScan3-137.jpg
          text: 'Probably 1998'
      - - name: TurboScan3-138.jpg
          text: 'Probably 1998'
        - name: TurboScan3-139.jpg
          text: 'Probably 1998'
        - name: TurboScan3-140.jpg
          text: 'Probably 1998'
      - - name: TurboScan3-141.jpg
          text: 'Probably 1998'
        - name: TurboScan3-142.jpg
          text: 'Probably 1998'
        - name: TurboScan3-143.jpg
          text: 'Probably 1998'
      - - name: TurboScan3-144.jpg
          text: 'Probably 1998'
        - name: TurboScan3-145.jpg
          text: 'Probably 1998'
        - name: TurboScan3-146.jpg
          text: 'Probably 1998'
      - - name: TurboScan3-147.jpg
          text: 'Probably 1998'
        - name: TurboScan3-148.jpg
          text: 'Probably 1998'
        - name: TurboScan3-149.jpg
          text: 'Developed 9/14/98: Walter by Victoria Ferry'
      - - name: TurboScan3-150.jpg
          text: 'Developed 9/14/98: Kjell and Justin G. at soccer practice.'
        - name: TurboScan3-151.jpg
          text: "Developed 9/14/98: Calvin Qu (Kjell's Best friend in 1998)"
        - name: TurboScan3-152.jpg
          text: 'Developed 9/14/98: Wi-Po'
      - - name: TurboScan3-153.jpg
          text: 'Developed 9/14/98: Wi-Po and Linda'
        - name: TurboScan3-154.jpg
          text: 'Developed 9/14/98: Walter and Linda'
        - name: TurboScan3-155.jpg
          text: 'Developed 9/14/98: Walter and Linda'
      - - name: TurboScan3-180.jpg
          text: '10/25/97 Soccer game end with St. Luke. Jeff, Pat Olson, Kjell, Jonah, Michael, Calvin, and Brandon'
        - name: TurboScan3-183.jpg
          text: ''
        - name: TurboScan4-011.jpg
          text: "9/4/1989 ILWU Labor Day Picnic - Gasworks Park, Seattle, WA. Emmett and Kjell's first intro to kite flying with Da's assistance."
      - - name: TurboScan4-012.jpg
          text: "10/14/1989 Huff 'n Puff: E and K at the validation checkers line - as each lap was completed, a checker would validate on card (placed on bike's front bars). 10 validations = 1 mile, recorded with a sticker."
        - name: TurboScan4-013.jpg
          text: "10/14/1989 Huff 'n Puff at St. Matthew's school to benefit the athetics' program."
        - name: TurboScan4-014.jpg
          text: "10/14/1989 Huff 'n Puff"
      - - name: TurboScan4-015.jpg
          text: "12/19/1989 Emmett (1st grade) removing angel costume at St. Matthew's school Christmas Program"
        - name: TurboScan4-016.jpg
          text: '12/19/1989 Alden Verdan forefront. First grade Mrs. Pepper in blue blouse on left rear of room.'
        - name: TurboScan4-017.jpg
          text: '12/19/1989'
      - - name: TurboScan4-018.jpg
          text: '12/19/1989'
        - name: TurboScan4-019.jpg
          text: "7/18/1990 Walter's Birthday"
        - name: TurboScan4-020.jpg
          text: "7/18/1990 Walter's Birthday"
      - - name: TurboScan4-021.jpg
          text: "7/18/1990 Walter's Birthday"
        - name: TurboScan4-026.jpg
          text: '4/23/1991 Emmett taking Ferry Ride with class'
        - name: TurboScan4-027.jpg
          text: '4/23/1991 Emmett taking Ferry Ride with class'
      - - name: TurboScan4-028.jpg
          text: '4/23/1991 Emmett taking Ferry Ride with class'
        - name: TurboScan4-029.jpg
          text: '5/15/1991 Emmett and Kjell with Grandma Mary and Aunt Nora'
        - name: TurboScan4-030.jpg
          text: '6/25/1991 Tiger Cubs (Emmett) advancing to Bobcat status'
      - - name: TurboScan4-031.jpg
          text: '6/25/1991 Tiger Cubs (Emmett) advancing to Bobcat status'
        - name: TurboScan4-032.jpg
          text: '6/25/1991 Tiger Cubs (Emmett) advancing to Bobcat status'
        - name: TurboScan4-033.jpg
          text: '9/13/1990 Emmett School Photo (age 7, 2nd grade)'
      - - name: TurboScan4-034.jpg
          text: '2/24/1992 Emmett'
        - name: TurboScan4-035.jpg
          text: '2/24/1992 Emmett'
        - name: TurboScan4-036.jpg
          text: '2/24/1992 Emmett'
      - - name: TurboScan4-037.jpg
          text: '2/24/1992 Emmett'
        - name: TurboScan4-038.jpg
          text: '1991-1992 Emmett's 3rd Grade Class Photo'
        - name: TurboScan4-039.jpg
          text: '6/6/92 Emmett's Birthday Party at Highland Ice Arena'
      - - name: TurboScan4-040.jpg
          text: "6/6/92 Emmett's Birthday Party at Highland Ice Arena"
        - name: TurboScan4-041.jpg
          text: '6/6/92 Emmett's Birthday Party at Highland Ice Arena'
        - name: TurboScan4-042.jpg
          text: '6/6/92 Emmett's Birthday Party at Highland Ice Arena'
      - - name: TurboScan4-043.jpg
          text: '6/6/92 Emmett's Birthday Party at Highland Ice Arena (Kjell, Patrick Walton, Wi-Gung, Linda)'
        - name: TurboScan4-044.jpg
          text: "7/18/1992 Birthday Dinner for Walter Connelly at Tony Roma's Lynnwood, WA. 50th. Comissioned tie by Laura Baker gift from Linda to Walter."
        - name: TurboScan4-045.jpg
          text: 'February 1992 Family Heritage Notebook'
      - - name: TurboScan4-046.jpg
          text: '9/29/1992 Emmett Connelly (9 Years Old) School Photo'
        - name: TurboScan4-063.jpg
          text: ''
        - name: TurboScan4-064.jpg
          text: ''
      - - name: TurboScan4-065.jpg
          text: ''
        - name: TurboScan4-066.jpg
          text: ''
        - name: TurboScan4-067.jpg
          text: ''
      - - name: TurboScan4-068.jpg
          text: ''
        - name: TurboScan4-069.jpg
          text: ''
