title: Of Elementary School Age (1988-1999)
sub_title: at St. Matthews
cover: TurboScan3-011.jpg
sections:
  - type: pictures-group
    images:
      - - TurboScan3-011.jpg
        - TurboScan3-012.jpg
        - TurboScan3-013.jpg
      - - TurboScan3-014.jpg
        - TurboScan3-015.jpg
        - TurboScan3-016.jpg
      - - TurboScan3-018.jpg
        - TurboScan3-019.jpg
        - TurboScan3-020.jpg
      - - TurboScan3-026.jpg
        - TurboScan3-027.jpg
        - TurboScan3-028.jpg
      - - TurboScan3-029.jpg
        - TurboScan3-030.jpg
        - TurboScan3-031.jpg
      - - TurboScan3-032.jpg
        - TurboScan3-033.jpg
        - TurboScan3-034.jpg
      - - TurboScan3-035.jpg
        - TurboScan3-036.jpg
        - TurboScan3-037.jpg
      - - TurboScan3-038.jpg
        - TurboScan3-116.jpg
        - TurboScan3-117.jpg
      - - TurboScan3-118.jpg
        - TurboScan3-119.jpg
        - TurboScan3-122.jpg
      - - TurboScan3-131.jpg
        - TurboScan3-132.jpg
        - TurboScan3-133.jpg
      - - TurboScan3-134.jpg
        - TurboScan3-135.jpg
        - TurboScan3-136.jpg
      - - TurboScan3-137.jpg
        - TurboScan3-138.jpg
        - TurboScan3-139.jpg
      - - TurboScan3-140.jpg
        - TurboScan3-141.jpg
        - TurboScan3-142.jpg
      - - TurboScan3-143.jpg
        - TurboScan3-144.jpg
        - TurboScan3-145.jpg
      - - TurboScan3-146.jpg
        - TurboScan3-147.jpg
        - TurboScan3-148.jpg
      - - TurboScan3-149.jpg
        - TurboScan3-150.jpg
        - TurboScan3-151.jpg
      - - TurboScan3-152.jpg
        - TurboScan3-153.jpg
        - TurboScan3-154.jpg
      - - TurboScan3-155.jpg
        - TurboScan3-156.jpg
        - TurboScan3-157.jpg
      - - TurboScan3-168.jpg
        - TurboScan3-176.jpg
        - TurboScan3-177.jpg
      - - TurboScan3-178.jpg
        - TurboScan3-180.jpg
        - TurboScan3-183.jpg
      - - TurboScan4-011.jpg
        - TurboScan4-012.jpg
        - TurboScan4-013.jpg
      - - TurboScan4-014.jpg
        - TurboScan4-015.jpg
        - TurboScan4-016.jpg
      - - TurboScan4-017.jpg
        - TurboScan4-018.jpg
        - TurboScan4-019.jpg
      - - TurboScan4-020.jpg
        - TurboScan4-021.jpg
        - TurboScan4-026.jpg
      - - TurboScan4-027.jpg
        - TurboScan4-028.jpg
        - TurboScan4-029.jpg
      - - TurboScan4-030.jpg
        - TurboScan4-031.jpg
        - TurboScan4-032.jpg
      - - TurboScan4-033.jpg
        - TurboScan4-034.jpg
        - TurboScan4-035.jpg
      - - TurboScan4-036.jpg
        - TurboScan4-037.jpg
        - TurboScan4-038.jpg
      - - TurboScan4-039.jpg
        - TurboScan4-040.jpg
        - TurboScan4-041.jpg
      - - TurboScan4-042.jpg
        - TurboScan4-043.jpg
        - TurboScan4-044.jpg
      - - TurboScan4-045.jpg
        - TurboScan4-046.jpg
        - TurboScan4-063.jpg
      - - TurboScan4-064.jpg
        - TurboScan4-065.jpg
        - TurboScan4-066.jpg
      - - TurboScan4-067.jpg
        - TurboScan4-068.jpg
        - TurboScan4-069.jpg
