title: Longshoring
sub_title: From the Waterfront
cover: TurboScan3-110.jpg
sections:
  - type: pictures-group
    images:
      - - name: TurboScan3-110.jpg
          text: ''
        - name: TurboScan3-111.jpg
          text: ''
