title: Longshoring
sub_title: From the Waterfront
cover: TurboScan3-110.jpg
sections:
  - type: pictures-group
    images:
      - - name: TurboScan3-110.jpg
          text: 'Developed 8/31/04 Kjell at Seattle Old Pier 25 Casual Hall'
        - name: TurboScan3-111.jpg
          text: 'Developed 8/31/04 Kjell at Seattle Old Pier 25 Casual Hall'
