title: Caught on Camera
sub_title: Not the most flattering pictures
cover: 'Photo Nov 22, 7 56 58 PM (1).jpg'
sections:
  - type: pictures-group
    images:
      - - name: 'Photo Nov 22, 7 56 47 PM.jpg'
          text: ''
        - name: 'Photo Nov 22, 7 56 48 PM.jpg'
          text: ''
        - name: 'Photo Nov 22, 7 56 53 PM (1).jpg'
          text: ''
      - - name: 'Photo Nov 22, 7 56 53 PM.jpg'
          text: ''
        - name: 'Photo Nov 22, 7 56 57 PM (1).jpg'
          text: ''
        - name: 'Photo Nov 22, 7 56 57 PM.jpg'
          text: ''
      - - name: 'Photo Nov 22, 7 56 58 PM (1).jpg'
          text: ''
        - name: TurboScan3-017.jpg
          text: ''
        - name: TurboScan3-039.jpg
          text: ''
      - - name: TurboScan3-040.jpg
          text: ''
        - name: TurboScan3-041.jpg
          text: ''
        - name: TurboScan3-109.jpg
          text: ''
      - - name: TurboScan3-161.jpg
          text: ''
