title: Walter & Linda Connelly
sub_title: Before having Kids
cover: 'Photo Nov 22, 7 57 04 PM.jpg'
sections:
  - type: pictures-group
    images:
      - - 'Photo Nov 22, 7 56 58 PM.jpg'
        - 'Photo Nov 22, 7 57 02 PM.jpg'
        - 'Photo Nov 22, 7 57 03 PM.jpg'
      - - 'Photo Nov 22, 7 57 04 PM (1).jpg'
        - 'Photo Nov 22, 7 57 04 PM.jpg'
        - 'Photo Nov 22, 7 57 05 PM (1).jpg'
      - - 'Photo Nov 22, 7 57 05 PM.jpg'
        - 'Photo Nov 22, 7 57 08 PM.jpg'
