title: Family Photos
sub_title: Not specific
cover: 'Photo Nov 22, 7 56 46 PM.jpg'
sections:
  - type: pictures-group
    images:
      - - name: 'Photo Nov 22, 7 56 46 PM.jpg'
          text: ''
        - name: TurboScan3-175.jpg
          text: ''
