title: Before Walter and Linda Got Married
sub_title: How youthful!
date: 1976-09-01
cover: TurboScan3-174.jpg
sections:
  - type: pictures-group
    images:
      - - name: TurboScan3-174.jpg
          text: "September 1976 - Our first picture together! :) In front of Walter's Mom and Dad's garage - while steaming oak strip to make a bodran drum (Irish, of course!). (Traditional wheat sifter, goat skin, copper tacks (rivets), a double-end handmade Irish-made drumming stick)."
        - name: 'Photo Nov 22, 7 57 02 PM.jpg'
          text: ''
        - name: 'Photo Nov 22, 7 57 03 PM.jpg'
          text: ''
      - - name: 'Photo Nov 22, 7 57 04 PM (1).jpg'
          text: ''
        - name: 'Photo Nov 22, 7 57 04 PM.jpg'
          text: ''
        - name: 'Photo Nov 22, 7 57 05 PM (1).jpg'
          text: ''
      - - name: 'Photo Nov 22, 7 57 05 PM.jpg'
          text: ''
        - name: 'Photo Nov 22, 7 57 08 PM.jpg'
          text: ''
        - name: TurboScan3-025.jpg
          text: ''
      - - name: TurboScan3-129.jpg
          text: '8/78 Walter and Walt'
        - name: TurboScan3-159.jpg
          text: ''
        - name: TurboScan3-167.jpg
          text: 'August 1978'
      - - name: TurboScan3-173.jpg
          text: 'November 1977'
        - name: 'Photo Nov 22, 7 56 58 PM.jpg'
          text: ''
        - name: TurboScan3-179.jpg
          text: ''
