title: Before Walter and Linda Got Married
sub_title: How youthful!
cover: TurboScan3-174.jpg
sections:
  - type: pictures-group
    images:
      - - name: 'Photo Nov 22, 7 56 58 PM.jpg'
          text: ''
        - name: 'Photo Nov 22, 7 57 02 PM.jpg'
          text: ''
        - name: 'Photo Nov 22, 7 57 03 PM.jpg'
          text: ''
      - - name: 'Photo Nov 22, 7 57 04 PM (1).jpg'
          text: ''
        - name: 'Photo Nov 22, 7 57 04 PM.jpg'
          text: ''
        - name: 'Photo Nov 22, 7 57 05 PM (1).jpg'
          text: ''
      - - name: 'Photo Nov 22, 7 57 05 PM.jpg'
          text: ''
        - name: 'Photo Nov 22, 7 57 08 PM.jpg'
          text: ''
        - name: TurboScan3-025.jpg
          text: ''
      - - name: TurboScan3-129.jpg
          text: ''
        - name: TurboScan3-159.jpg
          text: ''
        - name: TurboScan3-167.jpg
          text: ''
      - - name: TurboScan3-173.jpg
          text: ''
        - name: TurboScan3-174.jpg
          text: ''
        - name: TurboScan3-179.jpg
          text: ''
