title: Those Awkward Teenage Years
sub_title: '(Yes, they''re awkward)'
cover: 'Photo Nov 22, 7 56 56 PM.jpg'
sections:
  - type: pictures-group
    images:
      - - 'Photo Nov 22, 7 56 45 PM (1).jpg'
        - 'Photo Nov 22, 7 56 46 PM (1).jpg'
        - 'Photo Nov 22, 7 56 47 PM.jpg'
      - - 'Photo Nov 22, 7 56 48 PM.jpg'
        - 'Photo Nov 22, 7 56 52 PM.jpg'
        - 'Photo Nov 22, 7 56 53 PM (1).jpg'
      - - 'Photo Nov 22, 7 56 53 PM.jpg'
        - 'Photo Nov 22, 7 56 56 PM.jpg'
        - 'Photo Nov 22, 7 56 57 PM (1).jpg'
      - - 'Photo Nov 22, 7 56 57 PM.jpg'
        - 'Photo Nov 22, 7 56 58 PM (1).jpg'
  - type: pictures-group
    images:
      - - TurboScan3-017.jpg
        - TurboScan3-039.jpg
        - TurboScan3-040.jpg
      - - TurboScan3-041.jpg
        - TurboScan3-042.jpg
        - TurboScan3-043.jpg
      - - TurboScan3-045.jpg
        - TurboScan3-046.jpg
        - TurboScan3-047.jpg
      - - TurboScan3-076.jpg
        - TurboScan3-077.jpg
        - TurboScan3-078.jpg
      - - TurboScan3-079.jpg
        - TurboScan3-080.jpg
        - TurboScan3-086.jpg
      - - TurboScan3-087.jpg
        - TurboScan3-088.jpg
        - TurboScan3-089.jpg
      - - TurboScan3-090.jpg
        - TurboScan3-091.jpg
        - TurboScan3-092.jpg
      - - TurboScan3-107.jpg
        - TurboScan3-108.jpg
        - TurboScan3-109.jpg
      - - TurboScan3-161.jpg
