title: Growing up through Childhood
sub_title: (of Emmett and Kjell Connelly)
cover: 'Photo Nov 22, 7 56 45 PM.jpg'
sections:
  - type: pictures-group
    images:
      - - 'Photo Nov 22, 7 56 45 PM.jpg'
        - 'Photo Nov 22, 7 56 59 PM (1).jpg'
        - 'Photo Nov 22, 7 56 59 PM.jpg'
      - - 'Photo Nov 22, 7 57 00 PM (1).jpg'
        - 'Photo Nov 22, 7 57 00 PM.jpg'
        - 'Photo Nov 22, 7 57 01 PM.jpg'
      - - 'Photo Nov 22, 7 57 05 PM (2).jpg'
        - 'Photo Nov 22, 7 57 06 PM.jpg'
        - 'Photo Nov 22, 7 57 07 PM (1).jpg'
      - - 'Photo Nov 22, 7 57 07 PM.jpg'
