title: A Wonderful Snow Day with Mom
sub_title: Kjell and Linda
date: 1996-11-20
cover: TurboScan3-044.jpg
sections:
  - type: pictures-group
    images:
      - - name: TurboScan3-044.jpg
          text: ''
        - name: TurboScan3-048.jpg
          text: ''
        - name: TurboScan3-049.jpg
          text: ''
      - - name: TurboScan3-050.jpg
          text: ''
        - name: TurboScan3-051.jpg
          text: ''
        - name: TurboScan3-052.jpg
          text: ''
      - - name: TurboScan3-053.jpg
          text: ''
        - name: TurboScan3-054.jpg
          text: ''
        - name: TurboScan3-055.jpg
          text: ''
      - - name: TurboScan3-056.jpg
          text: ''
        - name: TurboScan3-057.jpg
          text: ''
        - name: TurboScan3-058.jpg
          text: ''
      - - name: TurboScan3-059.jpg
          text: ''
        - name: TurboScan3-060.jpg
          text: ''
        - name: TurboScan3-061.jpg
          text: ''
      - - name: TurboScan3-062.jpg
          text: ''
        - name: TurboScan3-063.jpg
          text: ''
