title: A Wonderful Snow Day with Mom
sub_title: Kjell and Linda
cover: TurboScan3-044.jpg
sections:
  - type: pictures-group
    images:
      - - TurboScan3-044.jpg
        - TurboScan3-048.jpg
        - TurboScan3-049.jpg
      - - TurboScan3-050.jpg
        - TurboScan3-051.jpg
        - TurboScan3-052.jpg
      - - TurboScan3-053.jpg
        - TurboScan3-054.jpg
        - TurboScan3-055.jpg
      - - TurboScan3-056.jpg
        - TurboScan3-057.jpg
        - TurboScan3-058.jpg
      - - TurboScan3-059.jpg
        - TurboScan3-060.jpg
        - TurboScan3-061.jpg
      - - TurboScan3-062.jpg
        - TurboScan3-063.jpg
