title: An Trip to Ireland w/o the Kids
sub_title: Walter, Linda, Mary
cover: TurboScan3-064.jpg
sections:
  - type: pictures-group
    images:
      - - TurboScan3-064.jpg
        - TurboScan3-065.jpg
        - TurboScan3-066.jpg
      - - TurboScan3-067.jpg
        - TurboScan3-068.jpg
        - TurboScan3-069.jpg
      - - TurboScan3-070.jpg
        - TurboScan3-071.jpg
        - TurboScan3-072.jpg
      - - TurboScan3-073.jpg
        - TurboScan3-074.jpg
        - TurboScan3-075.jpg
      - - TurboScan3-081.jpg
        - TurboScan3-082.jpg
        - TurboScan3-083.jpg
      - - TurboScan3-084.jpg
        - TurboScan3-085.jpg
        - TurboScan3-094.jpg
      - - TurboScan3-095.jpg
        - TurboScan3-096.jpg
        - TurboScan3-113.jpg
      - - TurboScan3-114.jpg
