title: An Trip to Ireland w/o the Kids
sub_title: 'Walter, Linda, Mary'
date: 1999-07-01
cover: TurboScan3-064.jpg
sections:
  - type: pictures-group
    images:
      - - name: 'Photo Nov 22, 7 56 59 PM (1).jpg'
          text: ''
        - name: 'Photo Nov 22, 7 56 59 PM.jpg'
          text: ''
        - name: 'Photo Nov 22, 7 57 00 PM (1).jpg'
          text: ''
      - - name: 'Photo Nov 22, 7 57 00 PM.jpg'
          text: ''
        - name: 'Photo Nov 22, 7 57 01 PM.jpg'
          text: ''
        - name: TurboScan3-064.jpg
          text: ''
      - - name: TurboScan3-065.jpg
          text: ''
        - name: TurboScan3-066.jpg
          text: ''
        - name: TurboScan3-067.jpg
          text: ''
      - - name: TurboScan3-068.jpg
          text: ''
        - name: TurboScan3-069.jpg
          text: ''
        - name: TurboScan3-070.jpg
          text: ''
      - - name: TurboScan3-071.jpg
          text: ''
        - name: TurboScan3-072.jpg
          text: ''
        - name: TurboScan3-073.jpg
          text: ''
      - - name: TurboScan3-074.jpg
          text: ''
        - name: TurboScan3-075.jpg
          text: ''
        - name: TurboScan3-081.jpg
          text: ''
      - - name: TurboScan3-082.jpg
          text: ''
        - name: TurboScan3-083.jpg
          text: ''
        - name: TurboScan3-084.jpg
          text: ''
      - - name: TurboScan3-085.jpg
          text: ''
        - name: TurboScan3-094.jpg
          text: ''
        - name: TurboScan3-095.jpg
          text: ''
      - - name: TurboScan3-096.jpg
          text: ''
        - name: TurboScan3-113.jpg
          text: ''
        - name: TurboScan3-114.jpg
          text: ''
