title: Walter and Linda's Wedding
sub_title: null
date: 1979-08-06
cover: TurboScan2-015.jpg
sections:
  - type: pictures-group
    images:
      - - name: TurboScan2-000.jpg
          text: ''
        - name: TurboScan2-001.jpg
          text: ''
        - name: TurboScan2-002.jpg
          text: ''
      - - name: TurboScan2-003.jpg
          text: ''
        - name: TurboScan2-004.jpg
          text: ''
        - name: TurboScan2-005.jpg
          text: ''
      - - name: TurboScan2-006.jpg
          text: ''
        - name: TurboScan2-007.jpg
          text: ''
        - name: TurboScan2-008.jpg
          text: ''
      - - name: TurboScan2-009.jpg
          text: ''
        - name: TurboScan2-010.jpg
          text: ''
        - name: TurboScan2-011.jpg
          text: ''
      - - name: TurboScan2-012.jpg
          text: ''
        - name: TurboScan2-013.jpg
          text: ''
        - name: TurboScan2-014.jpg
          text: ''
      - - name: TurboScan2-015.jpg
          text: ''
