title: At Courthouse
sub_title: To get legally married!
date: 1979-08-06
cover: TurboScan2-018.jpg
sections:
  - type: pictures-group
    images:
      - - name: TurboScan2-016.jpg
          text: ''
        - name: TurboScan2-017.jpg
          text: ''
        - name: TurboScan2-018.jpg
          text: ''
      - - name: TurboScan2-019.jpg
          text: ''
