title: Vehicles
sub_title: 'Cars, Motorcycles, etc'
cover: TurboScan3-112.jpg
sections:
  - type: bordered-picture
    image:
      name: TurboScan3-112.jpg
      text: "Developed 8/31/04 Emmett's Subaru got hit by another car"
